### ISSUE TITLE
[App] The details are showing in English for 10-20 sec, while scanning the QR code in Telugu version.

### ISSUE THREAD

**Issue by Sarada431** [thundersoft-india/automated-ticketing-system#29]

**Comment by HariniNarisetty** [comment]
Precondition: ATS app should be installed.

Steps to reproduce:
       1. Launch the ATS app
       2. Scan QR code
      
Expected Result: All Telugu details should be displayed on the home screen

Actual Result: Observed English details for 10-20sec

Priority | P2
Severity | S2
Reproducibility | 5/5

**Comment by vanukurusaradha** [comment]
Precondition: ATS app should be install

Steps to reproduce:
1. Launch ATS app
2. Scan QR code

Expected Result: All Telugu details should be display on the home screen

Actual Result: Observed English details for 10-20secs

 
Priority | P2
Severity | S2
Reproducibility | 5/5

**Comment by ruthvik-cse** [comment]
It is taking only 2 seconds to change from english to telugu
